### ISSUE TITLE
5dims ore and bobslib 0.15.1

### ISSUE THREAD

**Issue by ttr** [McGuten/5DimsFactorioMods#1]
bobs library 0.15.x have naming chnages and in 0.15.0 there is legacy re-map file but in 0.15.1 it was removed which caused 5dims ore to crash during factorio start.

in data-updates all occurrences of generate_ore need to be replaces with resource.generate

**Comment by McGuten** [comment]
that is fixed, i will upload in next release, thanks you ^^
