### ISSUE TITLE
Upload mod

### ISSUE THREAD

**Issue by zloi1604** [McGuten/5DimsFactorioMods#10]
Good day!
Please, upload mod to actual version. Some version on https://mods.factorio.com higher than here.

Is it possible to create new mine, same as mining-speed-1-range-1, mining-speed_1-range-2, mining-speed-2-range-1?

**Comment by zloi1604** [comment]
fix visualisation to oil refinery plant for factorio 0.15.
working_visualisations =
    {
      {
        north_position = util.by_pixel(34, -65),
        east_position = util.by_pixel(-52, -61),
        south_position = util.by_pixel(-59, -82),
        west_position = util.by_pixel(57, -58),
        animation =
        {
          filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
          line_length = 10,
          width = 20,
          height = 40,
          frame_count = 60,
          animation_speed = 0.75,
          shift = util.by_pixel(0, -14),
          hr_version = {
            filename = "__base__/graphics/entity/oil-refinery/hr-oil-refinery-fire.png",
            line_length = 10,
            width = 40,
            height = 81,
            frame_count = 60,
            animation_speed = 0.75,
            scale = 0.5,
            shift = util.by_pixel(0, -14.25),
          },
        },
        light = {intensity = 0.4, size = 6, color = {r = 1.0, g = 1.0, b = 1.0}}
      }
    },

**Comment by McGuten** [comment]
I dont know what you try to say :(
