### ISSUE TITLE
[5Dim Vehicles] Air Plane Speed issue

### ISSUE THREAD

**Issue by mikeloeven** [McGuten/5DimsFactorioMods#12]
I think there is a problem with the Airplane's top speed. It moves at the same rate as the APC which is far slower than the vanilla car. One would expect an aircraft to have a top speed exceeding that of the trains.

**Comment by McGuten** [comment]
Yes, the vehicles module need a total rework, but actually i have no time for it

**Comment by mikeloeven** [comment]
Actually i was playing around in the lua a quick dirty fix is to just drop a  from the plane's weight from 35000 to 3500 this gives it a good speed

**Comment by McGuten** [comment]
It is fixed in next release, thanks you ^^
