### ISSUE TITLE
Repeat of previous error

### ISSUE THREAD

**Issue by WildCard65** [McGuten/5DimsFactorioMods#13]
#8 has resurfaced but for another item (I added debugging to find out what caused it):

   6.164 Script item-group-changes.lua:237: water
   6.164 Script item-group-changes.lua:237: crude-oil
   6.164 Script item-group-changes.lua:237: heavy-oil
   6.164 Script item-group-changes.lua:237: light-oil
   6.164 Script item-group-changes.lua:237: petroleum-gas
   6.164 Script item-group-changes.lua:237: lubricant
   6.164 Script item-group-changes.lua:237: sulfuric-acid
   6.164 Script item-group-changes.lua:237: lithia-water
   6.164 Script item-group-changes.lua:237: pure-water
   6.164 Script item-group-changes.lua:237: liquid-air
   6.165 Error ModManager.cpp:851: Failed to load mod "5dim_core": __5dim_core__/data-updates.lua:2: __5dim_core__/prototypes/item-group-changes.lua:238: attempt to index field '?' (a nil value)

**Comment by McGuten** [comment]
I am playing in 0.15.13 with last version of 5Dim mod and all work fine so...

**Comment by WildCard65** [comment]
Is there any known mod incompatibilities with 5dim mods? (only other mod set I have is Bob's mods)

**Comment by McGuten** [comment]
I dont know, i think bob is compatible but... i dont know

**Comment by WildCard65** [comment]
I'm going to find out if there is one.

**Comment by WildCard65** [comment]
There's an incompatibility with 5dim core and this mod: https://mods.factorio.com/mods/Bobingabout/bobplates

**Comment by WildCard65** [comment]
More info, the following fluids are actually created by bobplates:
"pure-water", "liquid-air", "lithia-water", "hydrogen", "oxygen", "nitrogen", "chlorine", "hydrogen-chloride", "nitrogen-dioxide", "sulfur-dioxide", "nitric-acid", "tungstic-acid", "ferric-chloride-solution", "liquid-fuel"

**Comment by WildCard65** [comment]
Closing in favour of #14

**Comment by McGuten** [comment]
im working with Bob, for fix it ^^

**Comment by WildCard65** [comment]
That's great to hear.

**Comment by McGuten** [comment]
it is fixed, im uploading the mod changes (just core) ^^

**Comment by WildCard65** [comment]
@McGuten There is one final change that is required to truly fix: https://github.com/McGuten/5DimsFactorioMods/blob/master/5dim_core_0.15.9/data-final-fixes.lua#L94 (if statement required for healing_per_tick)
