### ISSUE TITLE
Under ground pipe is broken in transport.

### ISSUE THREAD

**Issue by 23johnw** [McGuten/5DimsFactorioMods#2]
![screenshot 4](https://cloud.githubusercontent.com/assets/16566849/25558610/2d24a1fc-2d22-11e7-969b-5b484898444e.png)

**Comment by McGuten** [comment]
how do you do it? i cant reproduce the problem

**Comment by 23johnw** [comment]
i had just core and transport.
it does it when i try connecting bent pipe.
Been playing around with it and it when i delete **require("prototypes.pipe-ground-1")** from transport config file and Pipe-ground-1.lua from prototypes its all fine. 
i will attach save file to.
[_autosave1.zip](https://github.com/McGuten/5DimsFactorioMods/files/966419/_autosave1.zip)

**Comment by 23johnw** [comment]
Just tried a new game with only core and transport, it still does it, i am using factorio 0.15.4

**Comment by 23johnw** [comment]
If i help i think i found the issue, the base,graphics,enity,pipe to ground has 2 images one hr and one without hr, i changed the filename in the mod pipe to ground to hr- image and the problem seemed to be solved.
![screenshot 5](https://cloud.githubusercontent.com/assets/16566849/25559314/36d34494-2d2f-11e7-969e-e80acc0c475c.png)

**Comment by McGuten** [comment]
The new version is uploaded, can you tell me if it was fixed?

**Comment by flexoo** [comment]
The underground pipes work perfect for me.

But found an other 2 missing locales in:

5dim_core_0.15.2/locale/en/locale.cfg

[item-group-name]
nuclear=Nuclear
decorations=Decorations

**Comment by McGuten** [comment]
i will upload the new version with the fix, thanks a lot ^^
