### ISSUE TITLE
Some locales left to fix

### ISSUE THREAD

**Issue by flexoo** [McGuten/5DimsFactorioMods#3]
Only 3:
5dim_automatization_0.15.2/locale/en/locale.cfg
-[item-name]
Assembling machine 4

-[entity-name]
Assembling machine 4

5dim_automatization_0.15.2/locale/es-ES/locale.cfg
-[entity-name]
5d-assembling-machine-4-22

**Comment by McGuten** [comment]
thanks you i will upload the new version now ^^
