### ISSUE TITLE
Last missing locales

### ISSUE THREAD

**Issue by flexoo** [McGuten/5DimsFactorioMods#4]
5dim_resources_0.15.1/locale/en/locale.cfg

[item-name]
tin-plate=Tin-plate -- You have it as 5d-tin-plate

5dim_automatization_0.15.2/locale/en/locale.cfg

[entity-name]
5d-inserter-smart-speed2-range1-close=Fast smart inserter near
5d-inserter-smart-speed2-range2=Fast smart long inserter
5d-inserter-smart-speed2-range2-close=Fast smart long inserter near
5d-inserter-smart-speed3-range1=Extra speed smart inserter
5d-inserter-smart-speed3-range1-close=Extra speed smart inserter near
5d-extreme-inserter-right-90d=Extra speed right inserter
5d-extreme-inserter-right-90d-close=Extra speed right inserter near
5d-extreme-inserter-left-90d=Extra speed left inserter
5d-extreme-inserter-left-90d-close=Extra speed left inserter near

5dim_module_0.15.1/locale/en/locale.cfg

[item-name]
5d-welder=Welder -- You wrote 5s-welder

[entity-name]
5d-welder=Welder

5dim_equipment_0.15.1/locale/en/locale.cfg

[equipment-name]
5d-personal-yellow-laser-defense-equipment=[insert name]
5d-personal-blue-laser-defense-equipment=[insert name]

**Comment by McGuten** [comment]
Thanks it will be fixed in next release
