### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LORD0DANZILA** [McGuten/5DimsFactorioMods#40]
idk why but it appeared after upd(I hope soon will be fix)
![default](https://user-images.githubusercontent.com/32709177/33798270-8a06d250-dd26-11e7-990b-c1b5488d6511.png)

**Comment by McGuten** [comment]
can you show me your mod folder?

**Comment by McGuten** [comment]
okey, i know the problem, upload the core mod please

**Comment by LORD0DANZILA** [comment]
i just reinstall all mods, and it work as usual

**Comment by McGuten** [comment]
nice, thanks you for comment :D
