### ISSUE TITLE
Can't Create Oil Refinery MK3 With Assembler MK5

### ISSUE THREAD

**Issue by brandon-schabel** [McGuten/5DimsFactorioMods#41]
The resources required to make an Oil Refinery MK3 exceeds what an Assembly MK5 can make. Also interested in helping out with developing this mod.

**Comment by McGuten** [comment]
It will be fixed on next release

About help us with dev... we are working and have no time to develop the mod...

**Comment by brandon-schabel** [comment]
Sounds good, will see what I can do.
