### ISSUE TITLE
Resources 0.16.3 causes crash at startup.

### ISSUE THREAD

**Issue by nvarin** [McGuten/5DimsFactorioMods#46]
Error in assignID, item with name 'process-unit' does not exist.

Source: 5d-industrial-furnace (recipe).

**Comment by McGuten** [comment]
what mods you have installed?

**Comment by nvarin** [comment]
Mod list: https://pastebin.com/rfnxvDkL

**Comment by McGuten** [comment]
okey i see the problem, i will fix it in few mins, thanks you for report ^^
