### ISSUE TITLE
5Dim Battlefield & Optera's Vehicle Grid

### ISSUE THREAD

**Issue by Ramdat** [McGuten/5DimsFactorioMods#47]
[Optera's Vehicle Grid mod](https://mods.factorio.com/mods/Optera/VehicleGrid) adds equipment grids to vehicles, to allow equipment to be inserted into them like modular armours. 

For vanilla vehicles, when equipment is inserted into a vehicle's grid and the player picks up the vehicle, the equipment remains inside the grid when it is placed down again. However, all equipment in the MK2 tank is deleted when it is picked up. Optera says this occurs when the item prototype is set incorrectly.  

This issue is easily reproducible. Simply place down an Mk2 tank, put any equipment inside, pick it up, put it back down and look inside the grid. 

This problem does not occur with 5Dim's locomotives, but I have not tested other vehicles.  

Also, tanks are supposed to have a 12x10 grid, but the Mk2 tank has a 8x8 grid as if it were a car.

**Comment by McGuten** [comment]
that is because Optera mod do it for vehicles without grid, but 5dims vehicles has grid (i do it) so...

**Comment by Ramdat** [comment]
Oh, thanks. I didn't realize that.  Since I fixed the other problem I'll close this issue now.
