### ISSUE TITLE
Laser Turret Changes

### ISSUE THREAD

**Issue by Ramdat** [McGuten/5DimsFactorioMods#49]
All existing tesla turrets placed in the world from the previous version are replaced with laser sniper turrets. This makes previous save games unplayable at high evolution because the laser sniper turrets do not have the DPS required to defend themselves as the tesla turrets did. Please fix this by replacing existing tesla turrets with the new electric turrets instead of the laser sniper turrets.

**Comment by McGuten** [comment]
The last changes should make it more  easy to kill big bitter, but we think all the turret should be use in defense

**Comment by Ramdat** [comment]
I have no problem with the addition of the laser sniper turret and agree that they should be used as well. 

However, you created the laser sniper turret by overwriting the old tesla-turret file, and then made a new electric-turret file that is the same as the old tesla-turret file. Because you did it this way, all the old tesla turrets on the entire map changed into laser sniper turrets because now the sniper laser turrets have the entity name of the old tesla turrets. 

If you give the tesla-turret file the stats of the electric turrets, and make a new file for the laser sniper turrets, the problem will be fixed.
