### ISSUE TITLE
Pump is absent

### ISSUE THREAD

**Issue by Hyomoto** [McGuten/5DimsFactorioMods#50]
The pump is missing, as well as it's upgrades.  They still show up under the technology to be unlocked, but aren't appearing in any of the categories.  Even using the search yields no results.

**Comment by McGuten** [comment]
![](https://i.gyazo.com/6e5a35812878404c24e29840bc9f4517.png)

Its working for me...

**Comment by Hyomoto** [comment]
Well, it's working.  You are right.  I'm not sure why it wasn't showing up before, but maybe it was just a weird glitch.  The 'energy' category wasn't showing up when I was searching Pump, so maybe it *was* there and the search was borked?  Either way, it seems to be an isolated issue.  Sorry for the false alarm :(

**Comment by McGuten** [comment]
It's okey dude ^^
