### ISSUE TITLE
Pumpjack MK2 is missing

### ISSUE THREAD

**Issue by WoaDmulL** [McGuten/5DimsFactorioMods#57]
The MK2 Pumpjack is not craftable by hand or in the assembling machines but the MK3 is showing.

![pumpjack](https://user-images.githubusercontent.com/11062661/34796639-c62297dc-f65e-11e7-9244-dd6a1a04f2d1.PNG)

**Comment by D10X1D0** [comment]
did you add/update the mod to a old save? tech-tree recipe unlocks might get glitched

**Comment by WoaDmulL** [comment]
![image](https://user-images.githubusercontent.com/11062661/34840166-cc7cebb0-f70c-11e7-9a6b-298f018a64f6.png)
It was already unlocked. The save is recent ( 0.16.15 ).

After I ran the command I could craft it.

**Comment by D10X1D0** [comment]
It was unlocked but not "enabled".
The game enables recipes for the player to use only when the research is finished at the lab.
Any mod that adds unlocks to tech-trees that might have being unlocked previously have to add a patch to check for this cases and "enable" the recipes.
IMO this is a silly thing and the game should auto-run a research unlocks check any time you add/delete a mod.

**Comment by McGuten** [comment]
I edit the readme.md, you can use this command to fix it ^^

And again, thanks you @D10X1D0
