### ISSUE TITLE
Recipe for mining drills

### ISSUE THREAD

**Issue by Grif-i** [McGuten/5DimsFactorioMods#59]
Is it intentional that the recipe for "5d-mining-drill-speed-2" is build from "5d-mining-range-1"   and speed-3 is build from range-2 ? 

I love your mods btw. keep up the nice work 👍

**Comment by D10X1D0** [comment]
IMO it must be a typo, it it is this changes should fix it.

**Comment by D10X1D0** [comment]
Github is missing git commands from the web-ui, sorry about the messi commits

**Comment by McGuten** [comment]
The recipe will be fixed in next release, thanks you @D10X1D0
