### ISSUE TITLE
Not an issue just an idea. Long reach mining,

### ISSUE THREAD

**Issue by 23johnw** [McGuten/5DimsFactorioMods#7]
I think you could add long reach mining to the project. I have done it as a small mod and adds an additional option in the mod menu. If you like then just use it.
[Ore Reach Mine_0.1.0.zip](https://github.com/McGuten/5DimsFactorioMods/files/967069/Ore.Reach.Mine_0.1.0.zip)

**Comment by McGuten** [comment]
Thanks you, i will add it in next release, thanks you a lot for you contribution ^^

**Comment by 23johnw** [comment]
Do you need discriptons for the mods?

**Comment by McGuten** [comment]
what you refer?

**Comment by 23johnw** [comment]
Just so people know what are in them. Not sure if you want them that way?

Was thinking some thing like this?

5DIM Core Mod

This mod is required for all 5Dim Factorio Mods.

---In options - mods menu, you can Select/Change---

**Enemies healing per tick multiplier**
    Change how quick the enemies heal.

**Enemies health multiplier**
    Change the health of the enemies

**Enemies Spawner (Nest) health multiplier**
    Change how hard the nest are to destroy.

**Players inventory size**
    Alter the inventory size of the player.

**Inventory stack multiplier**
    Multiply the stack size’s in your inventory.

**Hand Crafting speed**
    Change the hand crafting speed.

**Player healing per tick**
    Change how much you heal per tick.

**Player health**
    Change the health size of your player.

**Light radius**
   Changes the size of the light around your player at night.

**Long reach**
   Changes how far from the player you can build.

**Hand mining speed**
    Change the hand mining speed.

**Small tree collision box **
    Move through trees with ease.

**Comment by McGuten** [comment]
oh, nice, that is cool i will add it in next release ^^

**Comment by 23johnw** [comment]
Ok I forgot to mention that it also changes the menu. But I will add it and resend it you.

**Comment by McGuten** [comment]
Okay thanks you ^^

**Comment by 23johnw** [comment]
5DIM Core Mod

This mod is required for all 5Dim Factorio Mods.

**Add more categories to the crafting menu**

---In options - mods menu, you can Select/Change---

**Enemies’ healing per tick multiplier**
    Change how quick the enemies heal.

**Enemies’ health multiplier**
    Change the health of the enimies

**Enemies Spawner (Nest) health multiplier**
    Change how hard the nest are to destroy.

**Players inventory size**
    Alter the inventory size of the player.

**Inventory stack multiplier**
    Multiply the stack size’s in your inventory.

**Hand Crafting speed**
    Change the hand crafting speed.

**Player healing per tick**
    Change how much you heal per tick.

**Player health**
    Change the health size of your player.

**Light radius**
   Changes the size of the light around your player at night.

**Long reach**
   Changes how far from the player you can build.

**Long Mining**
   Changes how far from player, you can hand mine or chop down trees.

**Hand mining speed**
    Change the hand mining speed.

**Small tree collision box **
    Move through trees with ease.

**Comment by 23johnw** [comment]
5DIM Core Mod

This mod is required for all 5Dim Factorio Mods.

**Add more categories to the crafting menu**

---In options - mods menu, you can Select/Change---

**Enemies’ healing per tick multiplier**
    Change how quick the enemies heal.

**Enemies’ health multiplier**
    Change the health of the enimies

**Enemies Spawner (Nest) health multiplier**
    Change how hard the nest are to destroy.

**Players inventory size**
    Alter the inventory size of the player.

**Inventory stack multiplier**
    Multiply the stack size’s in your inventory.

**Hand Crafting speed**
    Change the hand crafting speed.

**Player healing per tick**
    Change how much you heal per tick.

**Player health**
    Change the health size of your player.

**Light radius**
   Changes the size of the light around your player at night.

**Long reach**
   Changes how far from the player you can build.

**Long Mining**
   Changes how far from player, you can hand mine or chop down trees.

**Hand mining speed**
    Change the hand mining speed.

**Small tree collision box**
    Move through trees with ease.

**Comment by 23johnw** [comment]
Thought maybe put it in the mods.factorio.com section for when people are looking to download the mod.
 I will work on the other mods, you will haver to bear with me as i in the process of moving house a bit chaotic at the moment

**Comment by 23johnw** [comment]
**5Dim Automatization**

**This mod pack offers a great variety of**

**Inserters**
    Yellow inserter near.
    Long inserter near. 
    Extra-long inserter.
    Extra-long inserter near.
    Fast speed inserter near.
    Fast long inserter.
    Fast long inserter near.
    Fast extra-long inserter.
    Fast extra-long inserter near.
    Extra speed inserter.
    Extra speed inserter near.
    Extra speed Long inserter.
    Extra speed Long inserter near.
    Extra speed extra Long inserter.
    Extra speed extra Long inserter near.
    Fast smart inserter near.
    Fast smart long inserter.
    Fast smart long inserter near.
    Extra speed smart long inserter.
    Extra speed smart long inserter near.
    Also there’s a variety of side inserters.


**Assembly machines**

    Assembly Machine 4
    (Crafting speed 1.75)

    Assembly Machine 5
    (Crafting speed 2.5)


**Chemical Plants**

   Chemical Plant MK2
   (Crafting Speed 2.5)

   Chemical Plant MK2
   (Crafting Speed 3.75)

**Oil Refinery’s**

    Oil Refinery MK2
    (Crafting speed 2.5)

    Oil Refinery MK3
    (Crafting speed 3.75)

**Comment by 23johnw** [comment]
**5Dim Automatization**

**This mod pack offers a great variety of**

**Inserters**
    Yellow inserter near.
    Long inserter near. 
    Extra-long inserter.
    Extra-long inserter near.
    Fast speed inserter near.
    Fast long inserter.
    Fast long inserter near.
    Fast extra-long inserter.
    Fast extra-long inserter near.
    Extra speed inserter.
    Extra speed inserter near.
    Extra speed Long inserter.
    Extra speed Long inserter near.
    Extra speed extra Long inserter.
    Extra speed extra Long inserter near.
    Fast smart inserter near.
    Fast smart long inserter.
    Fast smart long inserter near.
    Extra speed smart long inserter.
    Extra speed smart long inserter near.
    Also there’s a variety of side inserters.


**Assembly machines**

    Assembly Machine 4
    (Crafting speed 1.75)

    Assembly Machine 5
    (Crafting speed 2.5)


**Chemical Plants**

   Chemical Plant MK2
   (Crafting Speed 2.5)

   Chemical Plant MK2
   (Crafting Speed 3.75)

**Oil Refinery’s**

    Oil Refinery MK2
    (Crafting speed 2.5)

    Oil Refinery MK3
    (Crafting speed 3.75)

**Comment by 23johnw** [comment]
**5Dim Automatization**

**This mod pack offers a great variety of**

**Inserters**
    Yellow inserter near.
    Long inserter near. 
    Extra-long inserter.
    Extra-long inserter near.
    Fast speed inserter near.
    Fast long inserter.
    Fast long inserter near.
    Fast extra-long inserter.
    Fast extra-long inserter near.
    Extra speed inserter.
    Extra speed inserter near.
    Extra speed Long inserter.
    Extra speed Long inserter near.
    Extra speed extra Long inserter.
    Extra speed extra Long inserter near.
    Fast smart inserter near.
    Fast smart long inserter.
    Fast smart long inserter near.
    Extra speed smart long inserter.
    Extra speed smart long inserter near.
    Also there’s a variety of side inserters.

**Assembly Machines**

    Assembly Machine 4
    (Crafting Speed 1.75)

    Assembly Machine 5
    (Crafting Speed 2.5)


**Chemical Plants**

   Chemical Plant MK2
   (Crafting Speed 2.5)

   Chemical Plant MK2
   (Crafting Speed 3.75)

**Oil Refinery’s**

    Oil Refinery MK2
    (Crafting speed 2.5)

    Oil Refinery MK3
    (Crafting speed 3.75)

**Comment by McGuten** [comment]
just today i use a new template for all mods description, so i think it will be cool ^^
tomorrow i will add all of your texts, but if you have a time problem dont worry, I only have free weekends to do things on the mod so...

**Comment by 23johnw** [comment]
That's great, i will get round to it as and when i can. thanks

**Comment by 23johnw** [comment]
**5Dim Battlefield**

**This mod has many additions you weaponry and defense.**

**Changes the health, healing and spawn rate of the enemies. Making it slightly more challenging.**

**Metal Wall**
**Metal Gate**

**Small Gun Turret**
**Medium Gun Turret**
**Big Gun Turret**

**Small Laser turret**
**Medium Laser turret**
**Big Laser turret**
**Tesla Laser Turret**

**Tank MK2**
**Artillery Tank with artillery shells**

**Comment by 23johnw** [comment]
**5Dim Battlefield**

**This mod has many additions you weaponry and defense.**

**Changes the health, healing and spawn rate of the enemies. Making it slightly more challenging.**

**Defence**

    Metal Wall
    Metal Gate

**Turrets**

    Small Gun Turret
    Medium Gun Turret
    Big Gun Turret

    Small Laser turret
    Medium Laser turret
    Big Laser turret
    Tesla Laser Turret

**Vehicles**

    Tank MK2
   Artillery Tank with artillery shells

**Comment by 23johnw** [comment]
**5Dim Battlefield**

**This mod has many additions you weaponry and defense.**

**Changes the health, healing and spawn rate of the enemies. Making it slightly more challenging.**

**Defence**
   Metal Wall
   Metal Gate

**Turrets**

   Small Gun Turret
   Medium Gun Turret
   Big Gun Turret

   Small Laser turret
   Medium Laser turret
   Big Laser turret
   Tesla Laser Turret

**Vehicles**

   Tank MK2
   Artillery Tank with artillery shells

**Comment by 23johnw** [comment]
**5Dim Battlefield**

**This mod has many additions you weaponry and defense.**

**Changes the health, healing and spawn rate of the enemies. Making them slightly more challenging.**

**Also included**

**Defense**

   Metal Wall
   Metal Gate

**Turrets**

   Small Gun Turret
   Medium Gun Turret
   Big Gun Turret

   Small Laser turret
   Medium Laser turret
   Big Laser turret
   Tesla Laser Turret

**Vehicles**

   Tank MK2
   Artillery Tank with artillery shells

**Comment by 23johnw** [comment]
[5DIM Core Mod.txt](https://github.com/McGuten/5DimsFactorioMods/files/972023/5DIM.Core.Mod.txt)
[5Dim Battlefield.txt](https://github.com/McGuten/5DimsFactorioMods/files/972024/5Dim.Battlefield.txt)
[5Dim Automatization.txt](https://github.com/McGuten/5DimsFactorioMods/files/972025/5Dim.Automatization.txt)

To make the header in bold you need to put them in ** so i have put them as .txt docs so you can copy and paste easier.

**Comment by McGuten** [comment]
Thanks you!! ^^

**Comment by GimoXagros** [comment]
Good luck, McGuten.

**Comment by McGuten** [comment]
thanks you ^^
