### ISSUE TITLE
Recipes for 100 zinc, lead and gold from 85 ores use dust instead of ore.

### ISSUE THREAD

**Issue by Mr1Penguin** [McGuten/5DimsFactorioMods#78]
https://github.com/McGuten/5DimsFactorioMods/blob/70259561272638954ca50da96dae9c8d4ee9ef51/Factorio%200.16.X/5dim_ores_0.16.8/prototypes/resources.lua#L320-L367
I can fix it myself but only after 6th of June.

**Comment by McGuten** [comment]
I will fix it as soon as possible.
Thanks you for report
