### ISSUE TITLE
Update 0.15.10 - Error Loading 5dim_core - Item-group-chages:lua.236

### ISSUE THREAD

**Issue by KJayy** [McGuten/5DimsFactorioMods#8]
Hello,

After today's factorio update to 0.15.10 there appears to be an issue loading 5dim_core.

prototypes/item-group-changes.lua.236: attempt to index field'?'(a nil value)

[Imgur Link to Error Message](https://i.imgur.com/eSnFQ5c.png)

Thanks for all the work you do!

**Comment by Zehir** [comment]
Hello,

I check the line, it's probably because the steam is now a separate fluid from hot water;

Check the change log from [steam website](http://steamcommunity.com/games/427520/announcements/detail/1305326731381184903).

**Comment by Zehir** [comment]
For a quick fix, edit the file 5dim_core_0.15.6\prototypes\item-group-changes.lua
At line 232 add the if condition like this:
```
for _,fluid in pairs(data.raw.fluid) do
	if fluid.name ~= "steam" then
		local barrel = fluid.name .. "-barrel"
		local fill = "fill-" .. fluid.name .. "-barrel"
		local empty = "empty-" .. fluid.name .. "-barrel"
		data.raw.item[barrel].subgroup = "liquid-item"
		data.raw.recipe[fill].subgroup = "liquid-fill"
		data.raw.recipe[empty].subgroup = "liquid-empty"
	end
end
```

After if you using 5dim energy, edit the file:
5dim_energy_0.15.5\prototypes\boilers-2.lua and 5dim_energy_0.15.5\prototypes\boilers-3.lua (same modifications for both)
At line 114 add fluid_input and fluid_output between output_fluid_box and energy_consumption:
```
output_fluid_box =
    {
      base_area = 1,
      height = 2,
      pipe_covers = pipecoverspictures(),
      pipe_connections =
      {
        {type = "output", position = {0, -1.5}}
      },
      production_type = "output"
    },
    fluid_input =
    {
      name = "water",
      amount = 0.0
    },
    fluid_output =
    {
      name = "steam",
      amount = 0.0
    },
    energy_consumption = "1.8MW",
```

**Comment by Zehir** [comment]
I made a PR with this fix

**Comment by KJayy** [comment]
@Zehir Thank you, there is about a 0 percent chance I would have been able to figure that out!  👍

**Comment by cyxair** [comment]
Many thanks for this fix, works like a charm.

**Comment by McGuten** [comment]
Thanks you, it is updated now, thanks a lot for the report and for the pull ^^

**Comment by WildCard65** [comment]
Which version of 5dim core has the fix?

**Comment by cyxair** [comment]
Current version available on mods.factorio.com works well with Factorio 0.15.13
